
[env]

TERM = "xterm-256color"

[font]
size = 12

[window]
decorations = "none"
option_as_alt = "Both"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "PageUp", mods = "Control", action = "ReceiveChar" },
    { key = "PageDown", mods = "Control", action = "ReceiveChar" }
]

[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[terminal]
